name: Run Unit Tests in Parallel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_file: ["test_add.py", "test_subtract.py", "test_multiply.py", "test_divide.py", "test_power.py"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No dependencies found"

      - name: Run tests
        run: |
          python -m unittest discover -s . -p "${{ matrix.test_file }}" -v > ${{ matrix.test_file }}.txt 2>&1

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.test_file }}
          path: test_results_${{ matrix.test_file }}
